
interface SpawnOrder_Old {
    id: string, // role + count
    scheduleTick?: number,
    spawnTime: number,
    body: BodyPartConstant[],
    memory: CreepMemory,
}

interface SourceDetails {
    /** Position of source, packed. */
    packedPos: number
    /** Open positions around the source. */
    posCount: number
    /** Distance from the homeRoom's POI to the source. */
    dist?: number
    /** Carry parts required to fully transport the energy generated by the source. */
    carryReq?: number
}

interface RemoteDetails {
    [sourceId: Id<Source>]: SourceDetails,
    assignedHarvIds: Id<Creep>[],
    assignedTruckerIds: Id<Creep>[],
    assignedEngIds: Id<Creep>[],
}

