
interface SpawnOrder {
    id: string, // role + count
    scheduleTick?: number,
    spawnTime: number,
    body: BodyPartConstant[],
    memory: CreepMemory,
}

interface SourceDetails {
    /** Position of source, packed. */
    packedPos: number
    /** Open positions around the source. */
    posCount: number
    /** Distance from the homeRoom's POI to the source. */
    dist?: number
    /** Carry parts required to fully transport the energy generated by the source. */
    carryReq?: number
}

interface RemoteDetails {
    [sourceId: Id<Source>]: SourceDetails,
    assignedHarvIds: Id<Creep>[],
    assignedTruckerIds: Id<Creep>[],
    assignedEngIds: Id<Creep>[],
}

/** The form an inventory transfer request for the anchor should take.
 * @param supplyId the ID of the supply
 * @param targetId The ID of the destination structure. Must be a store structure.
 * @param resource The resource constant of the resource being moved.
 * @param qty The quantity to move.
 * */
interface AnchorRequest {
    supplyId?: Id<AnyStoreStructure>
    targetId: Id<AnyStoreStructure>
    resource: ResourceConstant
    qty?: number
}

