import { Coord } from "screeps-cartographer"
export class MineralDetail {
    id: Id<Mineral>
    mineralType: MineralConstant
    pos: Coord

    constructor(id: Id<Mineral>, mineralType: MineralConstant, pos: Coord) {
        this.id = id
        this.mineralType = mineralType
        this.pos = pos
    }
}

export class SourceDetail implements SourceDetails {
    /** Position of source, packed. */
    packedPos: number
    /** Open positions around the source. */
    posCount: number
    /** Distance from the homeRoom's POI to the source. */
    dist?: number
    /** Carry parts required to fully transport the energy generated by the source. */
    carryReq?: number

    constructor(packedPos: number, posCount: number) {
        this.packedPos = packedPos;
        this.posCount = posCount;
    }
}

